name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install --progress=false

      - name: Run linter
        run: npm run lint-ci

      - name: Run type checker
        run: npm run typecheck

      - name: Run unit tests
        run: npm run test

      - name: Test-Build
        run: npm run build
